version: 2
updates:
  # Enable version updates for npm (root package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "C-Elkins"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "C-Elkins"
    commit-message:
      prefix: "deps(frontend)"
      prefix-development: "deps-dev(frontend)"
      include: "scope"

  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "C-Elkins"
    commit-message:
      prefix: "deps(backend)"
      prefix-development: "deps-dev(backend)"
      include: "scope"

  # Control Center dependencies
  - package-ecosystem: "npm"
    directory: "/control-center"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "C-Elkins"
    commit-message:
      prefix: "deps(control-center)"
      prefix-development: "deps-dev(control-center)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    assignees:
      - "C-Elkins"
    commit-message:
      prefix: "ci"
      include: "scope"