# GitHub Sponsors configuration
# github: [C-Elkins] # Uncomment when you set up GitHub Sponsors
# patreon: username # Uncomment and replace with your Patreon username
# ko_fi: username # Uncomment and replace with your Ko-fi username
# custom: ["https://paypal.me/username", "https://www.buymeacoffee.com/username"] # Add your custom funding URLs

# Example configuration (uncomment and customize as needed):
# github: [C-Elkins]
# patreon: devstudio
# ko_fi: devstudio
# custom: ["https://paypal.me/devstudio", "https://www.buymeacoffee.com/devstudio"]